# Generated by Django 4.2.6 on 2023-12-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='TasLab',
        ),
    ]
